server.port=8081

# ✅ FIXED Mongo properties (Spring Boot correct keys)
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=certificate_db
spring.mongodb.uri=mongodb://localhost:27017/certificateDB
spring.thymeleaf.cache=false

# =========================
# Blockchain switch
# =========================
blockchain.mode=SIM

# -------- GANACHE SETTINGS ----------
blockchain.rpc-url=http://127.0.0.1:7545
blockchain.chain-id=1337
blockchain.private-key=0xb8d27acb81c7c403d0d3acec221b962c52c06a708a5560970a777fb822fb0ec0
blockchain.contract-address=0x4150E852FAe73eF6A882b14c7286E7C789dD3088
blockchain.gas-price=20000000000
blockchain.gas-limit=3000000

# helpful errors
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=never

# Public base url for QR verify
app.public-base-url=https://herta-crateral-unprudentially.ngrok-free.dev