server.port=8081

# ✅ Correct Mongo properties (Spring Boot)
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=certificate_db

spring.thymeleaf.cache=false

# =========================
# Blockchain switch
# =========================
# SIM  = runs fully inside your Spring project (no Ganache, no Remix)
# GANACHE = uses web3j + ganache RPC + deployed contract
blockchain.mode=SIM

# -------- GANACHE SETTINGS ----------
blockchain.rpc-url=http://127.0.0.1:7545
blockchain.chain-id=1337
blockchain.private-key=0x17159c459641ff3a5c0c01162cf2b785e6ab0763abbd4767181bb89fbb638b8e
blockchain.contract-address=0x1BE489D0b1D2BA5Aa4DBFe40e34261D80e8fd5C4
blockchain.gas-price=20000000000
blockchain.gas-limit=3000000

# helpful errors
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=never
